# ---- main workflow ---------------------------------------------------------------------------------------------
  
name: PorscheConnect

# ---- trigger ---------------------------------------------------------------------------------------------------

on:
  push:
    branches:
      - '**'        # matches every branch
      
# ---- jobs (run in parallel) ------------------------------------------------------------------------------------

jobs:

  # ---- test ------------------------------------------------------------------------------------------=---------

  test:
    name: Testing PorscheConnect
    runs-on: macos-11
    timeout-minutes: 8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Force XCode 13.0
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
      - name: Tests
        run: xcodebuild test -destination "platform=iOS Simulator,name=iPhone 13 Mini" -scheme "PorscheConnect"
